version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  node:
    build:
      context: .
      dockerfile: ./docker_compose/node/development/Dockerfile
    command: /start.sh
    volumes:
      - ./frontend:/exchange/frontend
    ports:
      - "3000:3000"

  nginx:
    build: ./docker_compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
