version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  node:
    build:
      context: .
      dockerfile: ./docker_compose/node/development/Dockerfile
    command: /start.sh
    volumes:
      - ./frontend:/exchange/frontend
    ports:
      - "3000:3000"
