version: '2'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'

  server:
    build: ./server
    working_dir: /code/server
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code/server
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    image: node:6.3
    ports:
      - "9000:9000"
    working_dir: /code/server
    volumes:
      - ./client:/code/client
    links:
      - server
