# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:50
from __future__ import unicode_literals

import cuser.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cuser.managers.UserManager()),
            ],
        ),
    ]
