export default function(){
   return[
     {
       id: 1,
       name: "classics",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 2,
       name: "experimental",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 3,
       name: "hidden sleeper",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 4,
       name: "new & popular",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 5,
       name: "talks",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 6,
       name: "potholderz",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
     {
       id: 7,
       name: "hipster trash",
       current_song: "Heros - David Bowie",
       next_song: "Piano Man - Billy Joe",
       previous_song: "One More Time - Daft Punk",
       listeners: 10,
     },
   ]
}
